### ISSUE TITLE
panic: Scope location \d+ must be greater than 1796001

### ISSUE THREAD

**Issue by lwb4** [amasad/esparse#1]
Hey Amjad,

Not sure exactly where/how to report this but I'm getting a strange compilation error on Repl.it that traces back to this repo.

Steps to reproduce:
1. Go to https://repl.it/@chalcidfly/boardgameio-template-1
2. Hit "run"
3. The console shows the following output:

```
node v12.16.1
 panic: Scope location 1795975 must be greater than 1796001 [recovered]
    panic: Scope location 1795975 must be greater than 1796001

goroutine 7 [running]:
github.com/amasad/esparse/parser.Parse.func1(0xc000fa3e58)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:7827 +0x6a
panic(0x882dc0, 0xc0013f94c0)
    /usr/lib/go-1.15/src/runtime/panic.go:969 +0x175
github.com/amasad/esparse/parser.(*parser).pushScopeForParsePass(0xc000134000, 0x2, 0x1b6787, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:272 +0x39f
github.com/amasad/esparse/parser.(*parser).parseParenExpr(0xc000134000, 0x1b6787, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1759 +0x6ab
github.com/amasad/esparse/parser.(*parser).parsePrefix(0xc000134000, 0x1, 0x0, 0xc000000000, 0x0, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1915 +0x14e9
github.com/amasad/esparse/parser.(*parser).parseExpr(0xc000134000, 0x1, 0x1b6778, 0x10ab3c0, 0xc001de6440)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2435 +0x45
github.com/amasad/esparse/parser.(*parser).parseAndDeclareDecls(0xc000134000, 0x101, 0xc001dea6e0, 0x1, 0x1)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:3182 +0x2b3
github.com/amasad/esparse/parser.(*parser).parseStmt(0xc000134000, 0x1, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4014 +0x6fa5
github.com/amasad/esparse/parser.(*parser).parseStmtsUpTo(0xc000134000, 0x12, 0x1, 0xc000fa2660, 0xc000042800, 0x7f0943255e98)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4834 +0xab
github.com/amasad/esparse/parser.(*parser).parseFnBodyStmts(0xc000134000, 0x0, 0x1acbde, 0x10ab3c0, 0xc001d95d68)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4817 +0xc5
github.com/amasad/esparse/parser.(*parser).parseArrowBody(0xc000134000, 0xc0012168a0, 0x1, 0x1, 0x0, 0xc0012168a0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1538 +0x167
github.com/amasad/esparse/parser.(*parser).parseParenExpr(0xc000134000, 0x1acbdd, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1763 +0x739
github.com/amasad/esparse/parser.(*parser).parsePrefix(0xc000134000, 0x1, 0x0, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:1915 +0x14e9
github.com/amasad/esparse/parser.(*parser).parseExpr(0xc000134000, 0x1, 0x8dd4e0, 0x0, 0x1)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2435 +0x45
github.com/amasad/esparse/parser.(*parser).parseCallArgs(0xc000134000, 0xc000fa30f8, 0x80130ee5, 0x34ef342c32d36e2b)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2933 +0x110
github.com/amasad/esparse/parser.(*parser).parseSuffix(0xc000134000, 0x1acbd2, 0x10ab560, 0xc001d95d58, 0x1, 0x0, 0x8c0ac0, 0x1, 0xc00138dd60)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2545 +0x2333
github.com/amasad/esparse/parser.(*parser).parseExpr(0xc000134000, 0x1, 0x1acbc0, 0x10ab3c0, 0xc001d95d50)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:2435 +0x85
github.com/amasad/esparse/parser.(*parser).parseAndDeclareDecls(0xc000134000, 0x10101, 0xc00138dbc0, 0x1, 0x1)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:3182 +0x2b3
github.com/amasad/esparse/parser.(*parser).parseStmt(0xc000134000, 0x101, 0x0, 0x0, 0x0)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4014 +0x6fa5
github.com/amasad/esparse/parser.(*parser).parseStmtsUpTo(0xc000134000, 0x0, 0x101, 0x2d, 0xc00002e570, 0x2d)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:4834 +0xab
github.com/amasad/esparse/parser.Parse(0xc000076120, 0x0, 0xc00002e570, 0x2d, 0xc00002e570, 0x2d, 0xc000926000, 0x1c5fd2, 0x1, 0x0, ...)
    /root/go/pkg/mod/github.com/amasad/esparse@v0.0.0-20200423043217-e2a08a964677/parser/parser.go:7851 +0x1d0
github.com/replit/upm/internal/backends/nodejs.parseFile(0x0, 0xc00002e570, 0x2d, 0xc00002e570, 0x2d, 0xc000926000, 0x1c5fd2, 0xc0000760c0)
    /upm/internal/backends/nodejs/grab.go:86 +0x158
created by github.com/replit/upm/internal/backends/nodejs.guessBareImports.func1
    /upm/internal/backends/nodejs/grab.go:136 +0x431


Repl.it: Package operation failed.
```

Tried to figure out if it was a transient error by forking the repl but nope, same problem.

Maybe there's a Repl.it forum that would be better to report the bug, but here seems as good as anywhere.

Thanks,
chalcidfly

**Comment by lwb4** [comment]
The issue still manifests on that repl, but in another fork I deleted the auto-generated JS files (which idk why esbuild is reading those) and re-ran, and it works. Weird!
